#!/usr/bin/env python
"""Entry point for the REINVENT 4 **fixed-reward** (single-shot) run — a ROUTE-LESS SMILES baseline
for the LSD-Flow library-efficiency benchmark, in the same class as S3-GFN (`[kim2026s3gfn]`).

The fixed-reward counterpart of the RxnFlow / FragGFN / SCENT / S3-GFN entrants: optimize REINVENT's
ChEMBL-pretrained SMILES RNN once, by reinforcement learning, against a FROZEN reward, then sample a
candidate pool and emit it in the standard candidate-dataset format. REINVENT has no reaction model,
so its molecules carry no route: emitted with ``has_route=0``, and a *library* built from them must
have its shared intermediates recovered post-hoc (MultiAiZ -> SPARROW).

TWO INVOCATIONS, MATCHING THE S3-GFN PROTOCOL EXACTLY.

  1. ``run_type = "staged_learning"`` — the RL run, scored by our ``GlueSurrogate`` plugin component
     (validation/generators/reinvent/plugins/...). Writes an agent checkpoint.
  2. ``run_type = "sampling"`` — draw the candidate pool from the TRAINED agent.

Step 2 is not a detail. REINVENT's RL trace contains every molecule it ever tried, including tens of
thousands from early, untrained steps; harvesting that trace would hand the downstream top-500 pool
builder a far larger and differently-distributed candidate set than S3-GFN's 2,000 post-training
samples, and the pool would no longer be comparable. Sampling from the final agent is the same
protocol ``run_s3gfn_fixed.py::_sample_pool`` follows.

REWARD PARITY. The scoring component optimizes the identical frozen reward as every other entrant
(``fixed_reward.py``: the Bengio-2021 sEH MPNN, or the cached TDC DRD2 oracle). REINVENT needs each
component mapped into ``[0, 1]``, which is done with a declarative ``transform`` written into the
generated TOML from ``reward.transform`` in our YAML — so the one knob that shapes what REINVENT
chases is visible in the run config, not buried in code. The pool is then RE-SCORED on the RAW value,
which is the scale the benchmark's mode gate uses (sEH ``> 7.0``, DRD2 ``> 0.5``).

Run (from repo root, reinvent4 env; candidate emission shells to the rgfn env):
    conda run -n reinvent4 python validation/generators/reinvent/run_reinvent_fixed.py \
        --cfg validation/configs/reinvent_seh_fixed.yaml \
        --root-dir $SCRATCH/rgfn_runs/experiments
"""

import argparse
import csv
import datetime
import os
import subprocess
import sys
import time
from pathlib import Path

from omegaconf import OmegaConf

_REPO_ROOT = Path(__file__).resolve().parents[3]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

# Imported AFTER the sys.path bootstrap above: these adapters are executed as
# scripts, so `validation` is not importable until the repo root is on the path.
from validation.generators._trace import (
    trace_from_reinvent,
    unshape_docking,
    write_timing,
)

_CLONE = _REPO_ROOT / "external" / "reinvent"
_PLUGINS = _REPO_ROOT / "validation" / "generators" / "reinvent" / "plugins"


def _timestamp() -> str:
    return datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")


def _toml_scalar(v) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    return '"' + str(v).replace('"', '\\"') + '"'


def _write_training_toml(
    path: Path, *, run_dir: Path, prior: Path, chkpt: Path, reward_c: dict, rl_c: dict
) -> None:
    """Emit the staged_learning TOML. Written as text (not via a TOML lib) so the file a reviewer
    opens is the same shape as REINVENT's own documented example configs."""
    transform = dict(reward_c.get("transform") or {})
    ttype = transform.pop("type", "sigmoid") if transform else ""
    df = dict(rl_c.get("diversity_filter") or {})

    lines = [
        "# GENERATED by validation/generators/reinvent/run_reinvent_fixed.py — do not hand-edit.",
        "# No `seed` key: ReinventConfig is extra='forbid' and has no seed field, so it would be",
        "# a hard ValidationError. Seeding happens in _seeded_launcher.py — read it before adding one.",
        "# The frozen benchmark reward enters through the GlueSurrogate plugin component.",
        'run_type = "staged_learning"',
        f'device = "{rl_c.get("device", "cuda:0")}"',
        f'tb_logdir = "{run_dir / "tb_logs"}"',
        "",
        "[parameters]",
        f'summary_csv_prefix = "{run_dir / "staged_learning"}"',
        "use_checkpoint = false",
        "purge_memories = false",
        f'prior_file = "{prior}"',
        f'agent_file = "{prior}"',
        f"batch_size = {int(rl_c.get('batch_size', 128))}",
        "unique_sequences = true",
        "randomize_smiles = true",
        "",
        "[learning_strategy]",
        'type = "dap"',
        f"sigma = {int(rl_c.get('sigma', 128))}",
        f"rate = {float(rl_c.get('learning_rate', 1e-4))!r}",
        "",
    ]

    # The diversity filter is ON by design, not by default. REINVENT's RL is reward-MAXIMIZING and
    # will happily converge onto one scaffold; a pool that collapses cannot reach the benchmark's
    # 100-mode deliverable, and we would only discover that after paying ~2.25 h of MultiAiZ route
    # discovery on it. Enabling it is also the charitable setting — it is what a chemist chasing a
    # diverse library would switch on — and it is recorded here so the choice is auditable.
    if df:
        lines += ["[diversity_filter]"]
        lines += [f"{k} = {_toml_scalar(v)}" for k, v in df.items()]
        lines += [""]

    # ONE STAGE, ALWAYS. REINVENT's multi-stage mechanism looked like a way to get periodic
    # checkpoints without patching upstream -- each stage writes `chkpt_file` and carries the same
    # agent forward. It does NOT work under a fixed step budget: `optimize()` returns terminate=True
    # whenever a stage ends on max_steps, and run_staged_learning.py:372 then breaks out of the whole
    # stage loop ("Terminating all stages"). Since our budget guarantee is min_steps == max_steps,
    # every stage ends that way, so a 10-stage run executed stage 1 and stopped -- 16 steps instead
    # of 157, measured 2026-08-21. Multi-stage is for curriculum learning with SCORE-based
    # transitions. Periodic checkpoints come from the documented learning.py patch instead
    # (docs/PATCHES.md); see REINVENT_CHECKPOINT_EVERY.
    lines += [
        "[[stage]]",
        f'chkpt_file = "{chkpt}"',
        'termination = "simple"',
        # FIXED BUDGET: every stage must end on max_steps for every seed and target, or the training
        # budget would depend on how easy the target is and the cells would stop being comparable.
        # The guarantee is `min_steps == max_steps`, NOT the score bound: SimpleTerminator fires on
        # `step > min_steps and score >= max_score`, and step never exceeds max_steps, so the first
        # clause is unsatisfiable. max_score is belt-and-braces — and it must be <= 1.0, which
        # RLConfig enforces (1.1 is a hard ValidationError).
        "max_score = 1.0",
        f"min_steps = {int(rl_c.get('max_steps', 1000))}",
        f"max_steps = {int(rl_c.get('max_steps', 1000))}",
        "",
        "[stage.scoring]",
        'type = "arithmetic_mean"',
        "",
        "[[stage.scoring.component]]",
        "[stage.scoring.component.GlueSurrogate]",
        "",
        "[[stage.scoring.component.GlueSurrogate.endpoint]]",
        f'name = "{reward_c.get("type", "seh_proxy")}"',
        "weight = 1.0",
        f'params.reward_type = "{reward_c.get("type", "seh_proxy")}"',
        f'params.model_path = "{reward_c.get("model_path", "")}"',
        f'params.device = "{reward_c.get("device", "cpu")}"',
        # Docking-only; harmless (and defaulted) for the surrogate targets.
        f'params.oracle = "{reward_c.get("oracle", "")}"',
        f'params.workdir = "{run_dir / "reward_bridge"}"',
        f'params.norm = {float(reward_c.get("norm", 1.0))!r}',
        "",
    ]
    # No transform block when the reward is already on [0, 1] (DRD2 is a probability). Emitting an
    # identity-ish transform there would only add a knob that looks meaningful and is not.
    if ttype:
        lines += [f'transform.type = "{ttype}"']
        lines += [f"transform.{k} = {_toml_scalar(v)}" for k, v in transform.items()]
    path.write_text("\n".join(lines) + "\n")


def _write_sampling_toml(
    path: Path, *, model_file: Path, out_csv: Path, num_smiles: int, device: str
) -> None:
    path.write_text(
        "\n".join(
            [
                "# GENERATED — draw the candidate pool from the TRAINED agent (see module docstring).",
                'run_type = "sampling"',
                f'device = "{device}"',
                "",
                "[parameters]",
                f'model_file = "{model_file}"',
                f"output_file = '{out_csv}'",
                f"num_smiles = {int(num_smiles)}",
                "unique_molecules = true",
                "randomize_smiles = true",
            ]
        )
        + "\n"
    )


def _run_reinvent(
    toml_path: Path, log_path: Path, run_dir: Path, seed: int, ckpt_every: int = 0
) -> None:
    """Invoke REINVENT through our seeding launcher, with the plugin dir on PYTHONPATH.

    Not the plain `reinvent` console script: v4.5.11 cannot be seeded through its own interface (the
    config key is rejected by validation, so `set_seed` always receives None). `_seeded_launcher.py`
    documents the bug and fixes it. PYTHONHASHSEED is exported here rather than set in-process
    because the interpreter fixes hash randomization at startup.
    """
    env = os.environ.copy()
    env["PYTHONPATH"] = os.pathsep.join(filter(None, [str(_PLUGINS), env.get("PYTHONPATH", "")]))
    env["PYTHONHASHSEED"] = str(seed)
    # Periodic checkpoints, via the documented learning.py patch (docs/PATCHES.md). Observability
    # only: unset these and the run is byte-identical to upstream.
    if ckpt_every and int(ckpt_every) > 0:
        env["REINVENT_CHECKPOINT_EVERY"] = str(int(ckpt_every))
        env["REINVENT_CHECKPOINT_DIR"] = str(run_dir / "checkpoints")
    launcher = Path(__file__).resolve().parent / "_seeded_launcher.py"
    cmd = [sys.executable, str(launcher), str(seed), "-l", str(log_path), str(toml_path)]
    print(f"[RNV-FR] {' '.join(cmd)}", flush=True)
    proc = subprocess.run(cmd, cwd=str(run_dir), env=env)
    if proc.returncode != 0:
        raise SystemExit(
            f"[RNV-FR] reinvent exited {proc.returncode}; see {log_path}. NOTE: a missing "
            "GlueSurrogate component shows up here as a config error — re-run "
            "external/setup_reinvent.sh, whose verification step checks plugin discovery."
        )


def _read_sampled(out_csv: Path) -> list:
    """Unique, RDKit-valid, canonical SMILES from REINVENT's sampling CSV (column `SMILES`)."""
    from rdkit import Chem

    if not out_csv.exists():
        raise SystemExit(f"[RNV-FR] sampling produced no output at {out_csv}")
    seen = {}
    with open(out_csv, newline="") as fh:
        for row in csv.DictReader(fh):
            smi = row.get("SMILES") or row.get("smiles") or ""
            mol = Chem.MolFromSmiles(smi) if smi else None
            if mol is None:
                continue
            seen.setdefault(Chem.MolToSmiles(mol), None)
    return list(seen)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--cfg", required=True, help="YAML run config (validation/configs/reinvent_*.yaml)"
    )
    ap.add_argument("--seed", type=int, default=None, help="override RNG seed (else cfg.run.seed)")
    ap.add_argument("--root-dir", default=None, help="base run dir (else cfg.run.root_dir)")
    ap.add_argument("--run-dir", default=None, help="EXACT run dir (stable, no timestamp)")
    ap.add_argument("--max-steps", type=int, default=None, help="override RL steps (smoke)")
    ap.add_argument("--n-samples", type=int, default=None, help="override pool size (smoke)")
    ap.add_argument(
        "--device",
        default=None,
        help="override reinvent.device (e.g. cpu for a login-node smoke, where the GPU is shared)",
    )
    args = ap.parse_args()

    cfg = OmegaConf.load(args.cfg)
    run_c = OmegaConf.to_container(cfg.get("run", {}), resolve=True) or {}
    fr_c = OmegaConf.to_container(cfg.get("fixed_reward", {}), resolve=True) or {}
    reward_c = OmegaConf.to_container(cfg.get("reward", {}), resolve=True) or {}
    rl_c = OmegaConf.to_container(cfg.get("reinvent", {}), resolve=True) or {}

    seed = args.seed if args.seed is not None else int(run_c.get("seed", 42))
    if args.max_steps is not None:
        rl_c["max_steps"] = args.max_steps
    if args.n_samples is not None:
        fr_c["n_samples"] = args.n_samples
    if args.device is not None:
        rl_c["device"] = args.device

    n_samples = int(fr_c.get("n_samples", 2000))
    oversample = float(fr_c.get("sample_oversample", 6.0))
    system = fr_c.get("system", "seh")
    reward_name = fr_c.get("reward_name", "seh_proxy")
    score_units = fr_c.get("score_units", f"{reward_name} (higher is better)")

    if args.run_dir:
        run_dir = Path(args.run_dir)
    else:
        root = Path(args.root_dir or run_c.get("root_dir", "experiments"))
        run_dir = root / run_c.get("name", "fixed_reward/reinvent_seh") / _timestamp()
    run_dir.mkdir(parents=True, exist_ok=True)
    OmegaConf.save(cfg, run_dir / "run_config.yaml")
    # ...and the EFFECTIVE config. The line above writes the file as LOADED, so any CLI
    # override (--budget, --n-samples, ...) was absent from the run's own provenance —
    # which for a benchmark means a smoke and a campaign cell look identical on disk.
    OmegaConf.save(
        OmegaConf.create(
            {"run": run_c, "fixed_reward": fr_c, "reward": reward_c, "reinvent": rl_c}
        ),
        run_dir / "run_config_effective.yaml",
    )

    prior = Path(rl_c.get("prior_file") or (_CLONE / "priors" / "reinvent.prior")).resolve()
    if not prior.exists():
        raise SystemExit(
            f"[RNV-FR] prior not found at {prior} — run external/setup_reinvent.sh first."
        )
    chkpt = run_dir / "agent.chkpt"
    device = rl_c.get("device", "cuda:0")

    print(
        f"[RNV-FR] run_dir={run_dir} seed={seed} steps={rl_c.get('max_steps')} "
        f"reward={reward_c.get('type')} system={system}",
        flush=True,
    )

    # --- 1. RL against the frozen reward. ------------------------------------------------------
    train_toml = run_dir / "staged_learning.toml"
    _write_training_toml(
        train_toml,
        run_dir=run_dir,
        prior=prior,
        chkpt=chkpt,
        reward_c=reward_c,
        rl_c=rl_c,
    )
    run_t0 = time.time()
    t0 = time.time()
    # RESUME, mirroring the Saturn and S3-GFN runners. Stage 2 ("upsample until the pool holds N
    # diverse modes") re-invokes this script with a larger --n-samples, and without this check each
    # round would repeat the whole RL run to arrive at the agent already sitting on disk. Sampling
    # below loads `agent.chkpt` by path, so its presence is a complete resume for that purpose.
    if chkpt.exists():
        print(
            f"[RNV-FR] RESUME: {chkpt.name} already present -- skipping training and going straight "
            "to sampling. Delete it to force a retrain.",
            flush=True,
        )
        train_s = 0.0
    else:
        _run_reinvent(
            train_toml,
            run_dir / "staged_learning.log",
            run_dir,
            seed,
            ckpt_every=int(rl_c.get("checkpoint_every_steps", 0) or 0),
        )
        train_s = time.time() - t0
        print(f"[RNV-FR] training done in {train_s:.1f}s", flush=True)
    if not chkpt.exists():
        raise SystemExit(f"[RNV-FR] no agent checkpoint at {chkpt} — training did not complete.")

    # --- 2. Sample the candidate pool from the TRAINED agent. ----------------------------------
    sample_csv = run_dir / "sampling.csv"
    sample_toml = run_dir / "sampling.toml"
    _write_sampling_toml(
        sample_toml,
        model_file=chkpt,
        out_csv=sample_csv,
        num_smiles=int(n_samples * oversample),
        device=device,
    )
    t0 = time.time()
    _run_reinvent(sample_toml, run_dir / "sampling.log", run_dir, seed)
    pool = _read_sampled(sample_csv)[:n_samples]
    sample_s = time.time() - t0
    print(
        f"[RNV-FR] sampled {len(pool)} unique valid candidates in {sample_s:.1f}s",
        flush=True,
    )

    # A short pool is a real signal (a reward-maximizing RNN can collapse), not something to paper
    # over — but a pool a small fraction of target is a broken run, and the difference matters
    # because the next stage costs ~2.25 h of route discovery. Warn on the former, abort on the
    # latter, and never let either be silently read downstream as "this generator's ceiling".
    if len(pool) < n_samples:
        frac = len(pool) / n_samples
        msg = (
            f"[RNV-FR] pool is {len(pool)}/{n_samples} unique valid ({frac:.0%}) after "
            f"{int(n_samples * oversample)} draws"
        )
        if frac < 0.25:
            raise SystemExit(
                msg + " — aborting: that is a broken run, not mode collapse. "
                "Check sampling.log and the diversity-filter settings."
            )
        print(msg + " — CHECK MODE SATURATION before spending route discovery on it.", flush=True)

    # --- 3. Re-score on the RAW value (the mode-gate scale) and emit the candidate dataset. -----
    # Imported here, not at module scope, so the TOML-generation logic above stays importable (and
    # unit-checkable) from any env — the reward stack only exists inside `reinvent4`.
    from validation.generators.reinvent.fixed_reward import build_provider

    provider = build_provider(
        reward_type=reward_c.get("type", "seh_proxy"),
        device=reward_c.get("rescore_device", "cpu"),
        model_path=reward_c.get("model_path") or None,
        # Docking passthrough. Inert for the surrogate rewards (build_provider ignores them
        # unless reward_type == "docking"), so one call site serves all three targets.
        oracle=reward_c.get("oracle") or None,
        repo_root=str(_REPO_ROOT),
        norm=float(reward_c.get("norm", 1.0)),
        failed_score=float(reward_c.get("failed_score", 0.0)),
        oracle_args=dict(reward_c.get("oracle_args") or {}),
        workdir=str(run_dir / "reward_bridge"),
    )
    scores = provider.predict(pool)

    out_dir = run_dir / "fixed_reward"
    out_dir.mkdir(parents=True, exist_ok=True)
    pairs_path = out_dir / "pairs.csv"
    # RAW SCORE IS LOAD-BEARING FOR THE DOCKING CELLS. `scores` is the provider's higher-is-better
    # VALUE -- for docking that is clip(-vina), a positive number. The ClpP mode gate is -8.0 on the
    # RAW Vina energy (Logs/045), so without this column a docking pool cannot be gated at all.
    # None for the surrogates, where predict() already returns the raw oracle value.
    raws = provider.raw_scores(pool) if hasattr(provider, "raw_scores") else None
    with open(pairs_path, "w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["smiles", "score"] + (["raw_score"] if raws is not None else []))
        for i, (smi, sc) in enumerate(zip(pool, scores)):
            w.writerow([smi, sc] + ([raws[i]] if raws is not None else []))

    ingest_cmd = [
        "conda",
        "run",
        "--no-capture-output",
        "-n",
        "rgfn",
        "python",
        "scripts/ingest_candidates.py",
        "--pairs",
        str(pairs_path),
        "--out-dir",
        str(out_dir / "candidates"),
        "--generator",
        "reinvent",
        "--reward-name",
        reward_name,
        "--system",
        system,
        "--seed",
        str(seed),
        "--score-higher-is-better",
        "--score-units",
        score_units,
        "--source",
        str(run_dir),
    ]  # NOTE: no --routes -> has_route=0 (REINVENT carries no route structure)
    # ingest_candidates.py imports `glue` (-> rgfn -> dgl/graphbolt), which needs the rgfn env's
    # CUDA libs on LD_LIBRARY_PATH. Those must NOT leak into this (reinvent4) process, so the submit
    # wrapper passes them for the ingest child only — same contract as run_s3gfn_fixed.py.
    ingest_env = os.environ.copy()
    _ingest_ld = os.environ.get("RGFN_INGEST_LD_LIBRARY_PATH")
    if _ingest_ld:
        ingest_env["LD_LIBRARY_PATH"] = _ingest_ld
    print(f"[RNV-FR] ingest -> {' '.join(ingest_cmd)}", flush=True)
    subprocess.run(ingest_cmd, check=True, cwd=str(_REPO_ROOT), env=ingest_env)

    # Trace + timing, derived POST-HOC from staged_learning_1.csv and the stamped log. See the
    # Saturn adapter for why this is a conversion rather than a loop hook. Non-fatal by design.
    try:
        # DOCKING TRACES MUST CARRY RAW VINA, not the shaped value the GFN trains on. This
        # converter reads the oracle component's own column, which for docking is
        # clip(-vina/norm) -- so without unshaping, nine ClpP traces held positive 0..17 values and
        # not one row cleared the -8.0 gate, making each cell's entire training history read as
        # empty. Surrogate targets are already raw and must NOT be touched.
        _unshape = (
            unshape_docking(float(reward_c.get("norm", 1.0)))
            if reward_c.get("type") == "docking"
            else None
        )
        n = trace_from_reinvent(run_dir, unshape=_unshape)
        write_timing(
            run_dir / "timing.json",
            {"train_s": train_s, "sample_s": sample_s},
            total_s=time.time() - run_t0,
        )
        print(
            f"[RNV-FR] trace -> {run_dir / 'trace.csv'} ({n} rows); timing -> timing.json",
            flush=True,
        )
    except Exception as exc:  # noqa: BLE001
        print(
            f"[RNV-FR] WARNING: trace/timing not written ({type(exc).__name__}: {exc})", flush=True
        )

    print(f"[RNV-FR] done. candidates at {out_dir / 'candidates'}", flush=True)


if __name__ == "__main__":
    main()
